blank_issues_enabled: true
contact_links:
  - name: Discord Server
    url: https://discord.gg/plexidev
    about: Join our community here.
  - name: Server Captcha Bot
    url: https://top.gg/bot/captcha
    about: Learn more about & invite Server Captcha Bot for Discord.
  - name: Source Code Website Features/Bugs
    url: https://github.com/TrueXPixels/sourcecode-public/issues/new/choose
    about: Suggest features or create bug reports for the upcoming Source Code Website.
